/**
 * Platform-level Permissions
 * These are assigned to platform roles (super_admin, platform_admin, support_staff)
 */
export const PLATFORM_PERMISSIONS = {
  // Transaction Management
  VIEW_ALL_TRANSACTIONS: 'view_all_transactions',
  MANAGE_TRANSACTIONS: 'manage_transactions',
  REFUND_TRANSACTIONS: 'refund_transactions',

  // KYC Management
  VIEW_KYC_SUBMISSIONS: 'view_kyc_submissions',
  APPROVE_KYC: 'approve_kyc',
  REJECT_KYC: 'reject_kyc',

  // User Management
  VIEW_USERS: 'view_users',
  MANAGE_USERS: 'manage_users',
  SUSPEND_USERS: 'suspend_users',

  // Organization Management
  VIEW_ORGANIZATIONS: 'view_organizations',
  MANAGE_ORGANIZATIONS: 'manage_organizations',

  // Platform Configuration
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_LOGS: 'view_logs',
} as const;

/**
 * Organization-level Permissions
 * These are assigned to organization members based on their role
 */
export const ORGANIZATION_PERMISSIONS = {
  // Payment Pages
  VIEW_PAYMENT_PAGES: 'view_payment_pages',
  CREATE_PAYMENT_PAGES: 'create_payment_pages',
  EDIT_PAYMENT_PAGES: 'edit_payment_pages',
  DELETE_PAYMENT_PAGES: 'delete_payment_pages',

  // Transactions
  VIEW_TRANSACTIONS: 'view_transactions',
  EXPORT_TRANSACTIONS: 'export_transactions',

  // Disbursements
  VIEW_DISBURSEMENTS: 'view_disbursements',
  REQUEST_DISBURSEMENTS: 'request_disbursements',

  // Organization Settings
  VIEW_SETTINGS: 'view_settings',
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_MEMBERS: 'manage_members',
  MANAGE_BILLING: 'manage_billing',
} as const;

/**
 * Role Definitions
 */
export const PLATFORM_ROLES = {
  SUPER_ADMIN: 'super_admin',
  PLATFORM_ADMIN: 'platform_admin',
  SUPPORT_STAFF: 'support_staff',
  VENDOR: 'vendor',
} as const;

export const ORGANIZATION_ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  FINANCE: 'finance',
  OPERATOR: 'operator',
  VIEWER: 'viewer',
} as const;

/**
 * Permission Groups
 */
export const PERMISSION_GROUPS = {
  PLATFORM_ADMIN_PERMISSIONS: [
    PLATFORM_PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    PLATFORM_PERMISSIONS.MANAGE_TRANSACTIONS,
    PLATFORM_PERMISSIONS.REFUND_TRANSACTIONS,
    PLATFORM_PERMISSIONS.VIEW_KYC_SUBMISSIONS,
    PLATFORM_PERMISSIONS.APPROVE_KYC,
    PLATFORM_PERMISSIONS.REJECT_KYC,
    PLATFORM_PERMISSIONS.VIEW_USERS,
    PLATFORM_PERMISSIONS.MANAGE_USERS,
    PLATFORM_PERMISSIONS.VIEW_ORGANIZATIONS,
    PLATFORM_PERMISSIONS.MANAGE_ORGANIZATIONS,
  ],

  SUPPORT_STAFF_PERMISSIONS: [
    PLATFORM_PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    PLATFORM_PERMISSIONS.VIEW_KYC_SUBMISSIONS,
    PLATFORM_PERMISSIONS.VIEW_USERS,
    PLATFORM_PERMISSIONS.VIEW_ORGANIZATIONS,
  ],

  ORGANIZATION_OWNER_PERMISSIONS: [
    ORGANIZATION_PERMISSIONS.VIEW_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.CREATE_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.EDIT_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.DELETE_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.VIEW_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.EXPORT_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.VIEW_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.REQUEST_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.VIEW_SETTINGS,
    ORGANIZATION_PERMISSIONS.MANAGE_SETTINGS,
    ORGANIZATION_PERMISSIONS.MANAGE_MEMBERS,
    ORGANIZATION_PERMISSIONS.MANAGE_BILLING,
  ],

  ORGANIZATION_ADMIN_PERMISSIONS: [
    ORGANIZATION_PERMISSIONS.VIEW_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.CREATE_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.EDIT_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.DELETE_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.VIEW_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.EXPORT_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.VIEW_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.REQUEST_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.VIEW_SETTINGS,
    ORGANIZATION_PERMISSIONS.MANAGE_MEMBERS,
  ],

  ORGANIZATION_FINANCE_PERMISSIONS: [
    ORGANIZATION_PERMISSIONS.VIEW_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.EXPORT_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.VIEW_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.REQUEST_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.VIEW_SETTINGS,
  ],

  ORGANIZATION_OPERATOR_PERMISSIONS: [
    ORGANIZATION_PERMISSIONS.VIEW_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.CREATE_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.EDIT_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.VIEW_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.VIEW_DISBURSEMENTS,
  ],

  ORGANIZATION_VIEWER_PERMISSIONS: [
    ORGANIZATION_PERMISSIONS.VIEW_PAYMENT_PAGES,
    ORGANIZATION_PERMISSIONS.VIEW_TRANSACTIONS,
    ORGANIZATION_PERMISSIONS.VIEW_DISBURSEMENTS,
    ORGANIZATION_PERMISSIONS.VIEW_SETTINGS,
  ],
} as const;
